name: Release Build

on:
  release:
    types: [published]

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入 Release
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build desktopJar
        run: ./gradlew desktopJar

      - name: Install Conveyor
        run: |
          # 下载并安装 Conveyor CLI
          curl -L https://github.com/hydraulic-software/conveyor/releases/download/v8.0.0/conveyor-8.0.0-linux-x64.zip -o conveyor.zip
          unzip conveyor.zip
          echo "$(pwd)/conveyor-8.0.0/bin" >> $GITHUB_PATH

      - name: Generate Package with Conveyor
        run: |
          conveyor make --stacktrace site

      - name: Upload Package to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/*.zip
            output/*.deb
            output/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}