name: Release Build

on:
  release:
    types: [published]

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build desktopJar
        run: ./gradlew desktopJar

      - name: Find JAR file
        id: find-jar
        run: |
          JAR_PATH=$(find . -path '*/composeApp/build/libs/*.jar' -type f -print -quit)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "JAR_NAME=$(basename $JAR_PATH)" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.JAR_PATH }}
          asset_name: ${{ env.JAR_NAME }}
          asset_content_type: application/java-archive