name: Release Build

on:
  release:
    types: [published]

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入 Release
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build desktopJar
        run: ./gradlew desktopJar

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v17.0
        env:
          OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: make site
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1

      - name: Upload Package to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/*.zip
            output/*.deb
            output/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}